import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full fixed top-0 left-0 z-50 h-10vh">
          <Navbar />
        </div>
        <div className="bg-white pt-5 overflow-y-auto fixed top-10 left-0 w-full h-90">
          {children}
        </div>
      </body>
    </html>
  );
}
